### PR TITLE
Convert less to use bootstrap variables and mixins

### PR DESCRIPTION
**Pull request by Julusian**
The changes look like more than there is, as a different version of less appears to be in use.

### CODE REVIEW

**Comment by nakupanda** [comment]
Hi,

Just tried your changes and found font was small than before, will give you more feedback later.

Thanks for you contribution!

**Comment by Julusian** [comment]
It looks like something weird is going on with the css/less i forked from.
It appears that your css files arent compiled from the current version of the less.
I have created another pull request to fix this.
https://github.com/nakupanda/bootstrap3-dialog/pull/137

**Comment by nakupanda** [comment]
You're right, the less file was created by other contributor based on the css file that had been written, I think during the process something was missing.

**Comment by fabn** [comment]
Could this be rebased to use latest version? It would be very useful to use less file as is instead of copying and pasting it only to add default bootstrap variables.

**Comment by Julusian** [comment]
I've just pushed a rebased version

**Comment by nakupanda** [comment]
Merged into master, thank you.

If possible, I would suggest exporting .less file to /dist/less directory too.

**Pull request merged**
