### PR TITLE
fixed ORIGINAL_BODY_PADDING's value type bug

### PR DESCRIPTION
**Pull request by tangqian**
BootstrapDialogModal.ORIGINAL_BODY_PADDING's value may be "0 px",so it's should add parseInt function

### CODE REVIEW

**Comment by szegheo** [comment]
@nakupanda Please accept this PR, it also fixes #167

**Comment by nakupanda** [comment]
Sorry guys... reading this too late, and thanks for the code :)

**Comment by tangqian** [comment]
It's OK, I'am very glad that you reply to me. I am Chinese, so maybe I have some mistake  in the expression

**Comment by tangqian** [comment]
I'm in Shenzhen of China.  Are you in USA?

**Comment by nakupanda** [comment]
Shenzhen too, a code farmer :)

**Comment by tangqian** [comment]
@nakupanda Can you tell my your QQ or Email.I would like to ask you for advice. My QQ is 275855127

**Pull request merged**
