### PR TITLE
Hotkey option added for confirmation dialog and alert.

### PR DESCRIPTION
**Pull request by amirkhiz**
I think this will be ok. I added hotkey to alert too if you're ok with that.
Thanks

### CODE REVIEW

**Comment by nakupanda** [comment]
Merging

**Comment by nakupanda** [comment]
Done merging, thanks

**Comment by amirkhiz** [comment]
Thank you too.

**Comment by Codepadawan** [comment]
Great job @amirkhiz. @nakupanda  this is one of the most useful jquery plugins ever. Kudos.

**Pull request merged**
