### PR TITLE
Allow a mouseOver text for buttons

### PR DESCRIPTION
**Pull request by tabacha**
Hi,
thank you for your libary. I would like to add a mouseOver text to a button:

``` javascript
BootstrapDialog.show({
            message: 'Hi Apple!',
            buttons: [{
                label: 'Button 1',
                mouseOver: 'Mouse over Button 1'
            }, 
..
```

### CODE REVIEW

**Comment by nakupanda** [comment]
Hi,

Thanks for this code contribution.
'mouseOver' looks more like an even handler rather than a text hint, how about we name it just as 'title':
````
...
label: 'Button 1',
title: 'This is button 1',
action: ..
````

**Comment by tabacha** [comment]
I do not like 'title' so much, because I see no difference between label and title.  The effect of title is a mouseOver Popup.
But  I can change this. You are the owner of the project and have the dessission.

**Comment by coffy** [comment]
Hi, 
as per source code it's just html 'title' attribute. I vote for '**title**' property :)

**Comment by nakupanda** [comment]
@coffy thanks for the vote :)

@tabacha , there is nothing to do with the project ownership.
'mousOverPopupText' obviously looks too long, and as the idea owner, you don't like it to be 'title', so how about 'tooltip' ?

**Comment by tabacha** [comment]
tooltip sounds also good

**Comment by zeckdude** [comment]
+1 for tooltip

**Comment by tabacha** [comment]
@nakupanda can you please merge this pr?

**Comment by nakupanda** [comment]
Done merging, thanks.

**Pull request merged**
