### PR TITLE
Creates composer.json for use as a composer package (i.e. via packagist.org)

### PR DESCRIPTION
**Pull request by TiSiE**
I've created a simple composer.json so this can be installed with composer dependency manager.

### CODE REVIEW

**Comment by nakupanda** [comment]
Thank you very much :)

**Comment by TiSiE** [comment]
You're welcome. 

Your project is soon used in [YAWIK](https://github.com/cross-solution/YAWIK)

:)

**Comment by nfodev** [comment]
Hi,

Can this package be updated for composer (nakupanda/bootstrap3-dialog)? I'll modify composer.json for you if you want.

Thanks, and thanks for your great work!

**Comment by nakupanda** [comment]
it should be possible, please update if you can help, thanks

**Pull request merged**
